service: notenest-tag-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - Fn::GetAtt: [NoteNestTagsTable, Arn]

functions:
  tags:
    handler: handler.tags
    events:
      - http:
          path: tags
          method: post
      - http:
          path: tags/{id}
          method: get
      - http:
          path: tags/{id}
          method: delete
      - http:
          path: tags
          method: get

resources:
  Resources:
    NoteNestTagsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NoteNestTagsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
